apiVersion: v1
kind: Secret

metadata:
  name: backend-secret
  namespace: musync

type: Opaque

stringData:
  SECRET_KEY: QWERTYUIOPLKJHGFDSAZXCVBNMQWERTYUIOP
  EMAIL: enzoenajaf@gmail.com
  EMAIL_PASSWORD: dlvgvbpmiuolgnfh
  GOOGLE_CLIENT_ID: 1086481272617-hf9gauq9ot5mq18ncv9cbr4b7eghif9k.apps.googleusercontent.com
  SPOTIFY_CLIENT_ID: 08609dd22ab0473785469591a116165f
  SPOTIFY_CLIENT_SECRET: 2367d7fc8485492d91f95573fba9c047
  YOUTUBE_KEY2: AIzaSyBnWPIeBxsAGLcAufmFNW9Sil1aesGyy94
  NODE_ENV: production